# Generated by Django 3.0.3 on 2021-01-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210116_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='time',
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ManyToManyField(related_name='all_bids', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing',
            field=models.ManyToManyField(related_name='all_comments', to='auctions.Listing'),
        ),
    ]
