# Generated by Django 3.0.3 on 2021-01-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210116_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='datefield',
            field=models.DateField(auto_now_add=True),
        ),
    ]
