# Generated by Django 3.0.3 on 2021-01-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210117_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='datefield',
        ),
    ]
