# Generated by Django 3.0.3 on 2021-01-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_bid_datefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('NONE', 'Not applicable'), ('HOME', 'Home'), ('WORK', 'Work'), ('EXERCISE', 'Exercise')], default='NONE', max_length=64),
        ),
    ]
