# Generated by Django 3.0.3 on 2021-01-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210120_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
